### PR TITLE
Use Flask CLI

### PR DESCRIPTION
**Pull request by rohitdatta**
**Flask-Script has been [deprecated](https://github.com/smurfix/flask-script#deprecated) in favor of the Flask CLI**

**Changes proposed in this pull request:**

* Replace Flask-Script commands with Flask CLI
* Use new extension import standard such as `flask.ext.sqlalchemy` with `flask_sqlalchemy`

**Have you made sure to add:**
- [ ] Tests
- [X] Documentation

**Screenshots and GIFs**

No UI changes

**Deploy notes**

`Procfile` uses gunicorn in production which doesn't run the development server from `manage.py`.

**Any Additional Information**
Not required immediately, but this is a precursor to building the background worker off of Flask CLI as opposed to Flask-Script since it's now deprecated.

### CODE REVIEW

**Comment by fiatjaf** [comment]
I tried this but couldn't run `flask` on `0.0.0.0`, which I needed. Does the `run_debug` command still work? (I don't know if and how I tried to run it.)

**Comment by colevscode** [comment]
What needs to happen in order to merge this?

**Comment by rohitdatta** [comment]
I believe this works fine. I'd say we merge and deploy to staging. I tested it using `heroku local`

**Comment by fiatjaf** [comment]
I believe we should merge.

**Pull request merged**
