### PR TITLE
Multiple cc

### PR DESCRIPTION
**Pull request by rohitdatta**
**New feature**

**Changes proposed in this pull request:**

* Allow for a user to include multiple _cc email addresses by allowing for a list of emails separate by comma
* Also allow for same functionality with BCC

**Have you made sure to add:**
- [ ] Tests
- [X] Documentation

No tests for _cc exist currently, but maybe some should be added. It is just a standard feature in the SendGrid API though.

**Deploy notes**

None necessary

**Any Additional Information**

Not sure if adding the BCC field is too many options, but it might be nice if people want to receive a copy of submissions.

### CODE REVIEW

**Comment by colevscode** [comment]
Who has asked for this feature? Also are we adding bcc? Why?

I'm not convinced what the use case is

**Comment by rohitdatta** [comment]
This was on the list on the Trello features requested by customers and a few people asked. Not really sure about the BCC if that's a useful feature. I could see if being useful for those that want to silently receive a copy of submissions but I also think it could be abused so I'm not sure if it's a good addition or not. I do think we should allow for multiple CC however since we have gotten requests for that

**Comment by colevscode** [comment]
Yeah I'd prefer to hold off on bcc until we have more demand from users.
The only use I can imagine is if an email is going to a group of site
owners where anyone can reply without revealing other emails. However I'm
not sure how important hiding emails are when the owner of replying anyway.

**Comment by rohitdatta** [comment]
Makes sense, I'll remove it.

**Pull request merged**
