### PR TITLE
Fancy email

### LINKED ISSUE #74: Better Email Styling
The current emails received are very basic. Should make them look much nicer

**Is this a bug or new feature?** New feature

**Reproduction Steps:**

None

**Expected behavior:**

Emails should be mobile responsive and also look better.

**Observed behavior:**

Emails are very simple

### PR DESCRIPTION
**Pull request by rohitdatta**
**Fixes #74.**

**Changes proposed in this pull request:**

* Better looking email for all transaction actions:
  * Confirm email for new form
  * Form submission
  * Form reached limit
  * Create formspree account

**Have you made sure to add:**
- [ ] Tests
- [ ] Documentation

Existing tests/documentation work

**Screenshots and GIFs**

Sample email account confirmation
screen shot 2016-03-03 at 3 40 20 pm

**Deploy notes**

No changes necessary. Will work with exist infrastructure

**Any Additional Information**

None.

### CODE REVIEW

**Comment by fiatjaf** [comment]
I think this is really nice. Did you do it by hand, with all that inline styles?

**Comment by fiatjaf** [comment]
screenshot-trello-attachments s3 amazonaws com 2016-03-03 20-53-30

Small request: can we make the field names bold?

**Comment by rohitdatta** [comment]
No way! I was originally doing that and realized how hard it was, so I used [Premailer](http://premailer.dialect.ca/)

**Comment by colevscode** [comment]
This is cool but it means that if someone fills out a formspree -powered
contact form with a _reply_to, the user will end up replying to their
customer with all our branding. Users may not like this, although it will
provide free marketing for formspree.

I think for a free service this could be OK if people don't complain too
much. I think for the paid plan though, we should have an option to turn
off branded emails.

**Comment by colevscode** [comment]
I'm not a fan of the full color headers around the formspree logo. Let's
use the landing page as a model for the email design. White background with
a thin colored line between the header and content would be better I think.

**Comment by colevscode** [comment]
The more I think about this, the more I prefer plain text emails. Formspree
is a simple tool for web developers. Extremely minimalist design is part of
the brand. Using fancy HTML emails makes emails harder to parse by tools
like IFTTT.

Also these email designs are inconsistent with formpspree branding, and Im
not sure they can be. It may not be possible to use our homepage font in
the emails because it's from fontkit, but I'm not sure.

**Comment by fiatjaf** [comment]
I hate to say this, but we have already had a complaint: https://trello.com/c/4p6VcY3r

**Comment by rohitdatta** [comment]
Based on what I've seen on our Twitter, Facebook, and emails sent to the account, some users love it and some want the other version back. I think we can just add this as an option `<input type="text" name="_text" style="display:none" />` and then if that happens send one of the old-fashioned emails.

**Comment by colevscode** [comment]
I don't like the option. It makes our service more complicated. What makes
formspree different is that it's simple.

Our simple text emails are one of the best parts of formspree. It makes our
small marketing message on the bottom of each email stand out. It keeps
that our emails from feeling like a marketing email. It makes our emails
feel more personal.

**Pull request merged**
