### PR TITLE
Improve the expensive query so it is less expensive.

### PR DESCRIPTION
**Pull request by fiatjaf**
In the [last PR](https://github.com/formspree/formspree/pull/157) we've reduced the number of times that the expensive query which deletes old submissions for each for would run. In this one we're changing the query so it is, I hope, much better and faster and clear.

Basically, what this should be doing is:

```sql
DELETE FROM submissions
WHERE form_id = <current_form_id>
  AND id < (
    SELECT id FROM (
      SELECT id FROM submissions
      WHERE form_id = <current_form_id>
      LIMIT 1000
    ) AS last_1000_records
    LIMIT 1
  ) AS last_record_to_keep
```

I just wrote the query above in this GitHub window, because the actual code is using SQLAlchemy and is very confusing and produces totally unreadable SQL: `DELETE FROM submissions WHERE submiss
ions.form_id = %(form_id_1)s AND submissions.id < (SELECT anon_1.id AS anon_1_id 
FROM (SELECT submissions.id AS id 
FROM submissions 
WHERE submissions.form_id = %(form_id_2)s ORDER BY submissions.id DESC 
 LIMIT %(param_1)s) AS anon_1 ORDER BY anon_1.id 
 LIMIT %(param_2)s)`

Is this really cheaper than the current version? I would bet a lot on it.
Is there any bug there I didn't notice? The sorting by ids of the submissions seems tricky. I think it is right, and the tests are passing, but maybe the tests don't cover this fully.

### CODE REVIEW

**Comment by rohitdatta** [comment]
The raw SQL you wrote in GitHub does appear to be correct. However, I might suggest executing a [raw SQL statement](https://stackoverflow.com/a/23206636/3163830). If we parameterize this, with form_id as an int, I don't think we would have any SQL injection issues

**Comment by fiatjaf** [comment]
I'm for writing raw SQL everywhere, but since we're using SQLAlchemy already I thought that would be good to stick to it, so the whole app code doesn't look like a mess.

**Comment by rohitdatta** [comment]
I'm suggesting we do it only for such a complicated query. On the whole, I think having SQLAlchemy is nice for basic things, but for such a big query, let's avoid leaving it up to SQLAlchemy

**Comment by fiatjaf** [comment]
But I've already written the SQLAlchemy version of the query!

**Pull request closed without merging**
