### PR TITLE
Site-wide confirmations

### PR DESCRIPTION
**Pull request by fiatjaf**
**New feature**

**Changes proposed in this pull request:**

* The form creation API now supports creating forms that are pre-confirmed if the target email was already verified for the user account.
* The form creation API now supports creating forms verified site-wide. At the moment of the form creation an HTTP request is made to check for the presence of a verification file at the root path of the site that is being authorized.
* Adds a new boolean column to the `forms` table, named "sitewide".

**Have you made sure to add:**
- [x] Tests
- [ ] Documentation

**Demo**

http://formspree-fiatjaf.herokuapp.com/ (say your registered email there if you want a Gold account to test)

**Deploy notes**

Database migration: `heroku run python manage.py db upgrade --app formspree-asm`

### CODE REVIEW

**Comment by rohitdatta** [comment]
I might not have correctly understood it, but in this [line](https://github.com/fiatjaf/formspree/commit/f34aea0850e6d1d571c46d59cda00cf9857336b2#diff-12088bf911f94950c9492d4cf189e794R305) I don't think it accounts for the www subdomain. A lot of people expect this to also be confirmed, so can we set it up as a special case if it's a naked URL? I would say to use urlparse for this, and then go based on the number `.` but this doesn't work for the funky `.co.uk` domains and the few others like it.

**Comment by fiatjaf** [comment]
I think it should be something implemented for the `referrer_to_path` [function](https://github.com/formspree/formspree/blob/22c192b217c482a73791aa3d44349c8776f4244a/formspree/forms/helpers.py#L27-L34), what do you think?

**Comment by fiatjaf** [comment]
Perhaps we should just merge this: https://github.com/fiatjaf/formspree/commit/ac564afef92d1288a235d38f387bd57273c845bf

**Comment by fiatjaf** [comment]
Can we merge this already, @rohitdatta?

**Comment by rohitdatta** [comment]
I like this, the only thing I might suggest would be wording, because I was a little confused at first that I needed to create a file, since usually you have to upload a file. But this isn't really important right now, so let's just merge and then maybe make it clearer later.

**Comment by rohitdatta** [comment]
@fiatjaf I fixed the merge conflicts you are experiencing, so if you merge the PR I sent to your branch into your branch, we should be able to merge that branch into formspree master

**Comment by rohitdatta** [comment]
I'm going to merge this as is. We can fix any issues if needed and also based on customer feedback.

**Comment by rohitdatta** [comment]
@fiatjaf I'm going to let you handle deploying this since we'll also need to do a database upgrade and you're the most familiar with that. But since #83 is ready to deploy as long as @colevscode likes the design, I would prefer to merge that into master and then deploy everything at once.

**Comment by fiatjaf** [comment]
@rohitdatta Done.

**Pull request merged**
