### PR TITLE
New branded emails and support for _format

### LINKED ISSUE #82: _format doesn't work
`_format` option doesn't have any effect. It's a bug, I believe. The documentation explains that option, but in reality it has no effect. I keep receiving HTML emails, which show `_format` as a normal option.

### PR DESCRIPTION
**Pull request by rohitdatta**
**Fixes #82, #76, and #75.**

**Changes proposed in this pull request:**

* Model Formspree HTML emails after the Formspree website
* Introduce _format variable to allow users to roll back

**Have you made sure to add:**
- [ ] Tests
- [X] Documentation

**Screenshots and GIFs**

**New form confirmation** (download arrow was included by Gmail web client, but doesn't normally appear)
screen shot 2016-03-13 at 6 49 25 pm

**Form submission**
screen shot 2016-03-13 at 6 51 24 pm

**Deploy notes**

No migrations necessary, but do not deploy until all branding migrations can be completed.

**Any Additional Information**

The changes in this PR must be applied to the password reset emails form #80 before deployment to ensure consistent branding.

### CODE REVIEW

**Comment by rohitdatta** [comment]
@fiatjaf @colevscode Do you think this is ok, or should I make any additional changes? I want to get everything finalized before I fix the merge conflicts, since I would do this on the formspree repo, not my fork

**Comment by fiatjaf** [comment]
I'm satisfied.

But the conflicts should be fixed in another branch, which then is merged into master. Just like the GitHub "command line instructions" (button 40px above) says.

**Comment by rohitdatta** [comment]
I think I know how to do it. GitHub's instructions seem to be from the repository owner point of view, but I think I can merge formspree/master changes into my branch and then commit.

**Comment by colevscode** [comment]
Two suggestions: 

Please try to match spacing above and below the horizontal line. There should be more space between the body text and the line.

For the confirm button, can you use a simple green outline with square (not round) corners? See the buttons on the form at the bottom of formspree.io.

**Comment by colevscode** [comment]
More suggestions:

Confirmation email, second paragraph, last sentence:
"Note that you won't receive any further emails until you confirm."

Alert box:
"ALERT: You will not receive further emails until you confirm." (no link required, customer might think he needs to click "here" in the alert box, in addition to the confirm button.

Last paragraph below alert box: Remove it.

Footer text:
"Why did I receive this? 
Someone (hopefully you?) used your email with the Rohit Forms API on localhost:8000/. If this wasn't you, no worries. This is the only email you'll get. If you have any questions, feel free to shoot an email to <email>"

Other than the above recommendations, it looks GREAT!

**Comment by rohitdatta** [comment]
Done @colevscode. You can check out what it looks like on http://formspree-rohit.herokuapp.com again.

**Comment by colevscode** [comment]
Yup this looks good. Go for it.

At some point it would be cool to figure out why the content portion of the email has a margin along the right side. Ideally the content area would be centered and the same width as the footer. See below (the red box is narrower than the footer text).

screen shot 2016-03-15 at 11 44 23 pm

**Comment by rohitdatta** [comment]
I think that's because the red box isn't technically the full width of the container, but I can investigate that. It may also be related to the weird stuff you have to do with responsive HTML emails in tables, but if that's the case I should just be able to put the footer in a new row.

**Pull request merged**
