### PR TITLE
Move CAPTCHA to forms list and clean up styles

### PR DESCRIPTION
**Pull request by rohitdatta**
**Fixes issues raised by @colevscode in #137.**

**Changes proposed in this pull request:**

* Move reCAPTCHA toggle from submissions page to form modal
* Fixed HTML indentation
* Spelling fix

**Have you made sure to add:**
- [ ] Tests
- [ ] Documentation

**Screenshots and GIFs**

screen shot 2017-02-21 at 5 38 14 pm
screen shot 2017-02-21 at 5 39 40 pm

**Deploy notes**

None necessary, all changes are front end

**Any Additional Information**

### CODE REVIEW

**Comment by rohitdatta** [comment]
If there aren't any objections to this I'm going to merge it

**Comment by fiatjaf** [comment]
I have an objection!

**Comment by fiatjaf** [comment]
I prefer the button to disable reCAPTCHA where it already is. Why are you changing?

**Comment by fiatjaf** [comment]
I think we should somehow stop showing that form modal with the HTML If the form already has submissions.

Or have a more obvious link to the canonical form data page (the page with the form submissions history), instead of having it just at the submissions count.

**Comment by fiatjaf** [comment]
Can we merge this now and decide later what to do with the modal?

**Comment by rohitdatta** [comment]
Yes, that's good with me. Our mobile styles are actually broken in the current iteration and this fixes that

**Pull request merged**
