### PR TITLE
Add Google Analytics tracking

### PR DESCRIPTION
**Pull request by rohitdatta**
Add Google Analytics to all Formspree webpages

### CODE REVIEW

**Comment by fiatjaf** [comment]
Hey! You didn't follow the PR submission template!
I'm closing this PR because of this.

(Just kidding)

Where is the conversion tracking happening on this GA code you're committing? (I want to know that also for personal reasons, because I have never really understood Google Analytics and all those enourmous amounts of features).

**Comment by rohitdatta** [comment]
Wasn't sure if you still wanted to do that so I deleted it :p. But it's on the Google Analytics site, which you should have gotten an email for.

**Comment by rohitdatta** [comment]
Oh I see you're talking about tracking conversion rates. That I'm also not fully sure because I've never used it for a conversion product, but I believe that you need to set it up in the Google Analytics dashboard itself

**Comment by fiatjaf** [comment]
I also think that perhaps we could gain something from a little tracking, but, after thinking about it in the last 2 hours I don't think Google Analytics is the right tool for the job.

The only kind of conversion tracking we will be able to do with Google Analytics is from visitor to normal user, or visitor to Gold account. There's no way to track, for example, normal user to Gold account, nor to get information on which features are being used most.

I think we would be best with some kind of server-side tracking, using Segment.io and/or similar/related services.

Then, I imagine, we would be able to see with clarity which normal form user signed up to a Gold (or Silver) account and which Gold features are being used most, for example. What do you think?

**Comment by rohitdatta** [comment]
I hadn't even heard of segment.io but it definitely sounds like a better idea to get much better analytics tracking. I had wanted Google Analytics for getting some ballpark information about the site views, but I think it makes more sense just to integrate segment.io fully, which also supports Google Analytics.

**Comment by rohitdatta** [comment]
Closing and will instead use segment.io for analytics tracking

**Pull request closed without merging**
