### PR TITLE
store first submission on redis, send it on confirmation.

### PR DESCRIPTION
**Pull request by fiatjaf**
A revival of https://github.com/formspree/formspree/pull/142, because that got buried in the sand of force-pushs.

### CODE REVIEW

**Comment by rohitdatta** [comment]
Oops did not realize this had been merged in already. Are these all the same commits? If so we can go ahead and merge it

**Comment by fiatjaf** [comment]
I merged it, but couldn't test it on formspree-staging (oddly my test form was confirmed, but didn't show up in the database), so I didn't push it to formspree-asm.

What happens in formspree-staging? Is it using the same database as formspree-asm?

**Comment by fiatjaf** [comment]
Yes, same code. I've just tested it locally and it works fine. I think we can merge it now.

**Comment by rohitdatta** [comment]
Go for it

**Pull request merged**
