### PR TITLE
Remove reply_to dependency for _cc

### PR DESCRIPTION
**Pull request by tonyteate**
Enables cc'ing without requiring the reply_to field.

### CODE REVIEW

**Comment by rohitdatta** [comment]
This is a much better implementation for ensuring validity of every email. However, I'm not sure I understand your commit message/PR title. I don't believe however that there was ever a _replyto dependency for _cc. _replyto is an independent field and not required, so you can still have a _cc field without a _replyto.

**Comment by tonyteate** [comment]
I added the list comprehension only to simplify the existing code. The logic is the same. 

With regard to sending the email, in the original code block the `if` statement concerning the `cc` varialbe resides within the `if` statement concerning the `reply_to` variable. Therefore, the `data` object (dictionary) that is send w/ the request is not updated with the `cc` item if `reply_to` is either a "falsy" value (i.e. `_replyto` is not included in the api request) or if `reply_to` is an invalid email. 

In practice, this is the observed behavior, which is why I came searching for the codebase :smiley:

**Comment by rohitdatta** [comment]
Ah I see what you mean. I messed up tabs and spaces, so that's what caused the issue. Thanks for fixing that!

**Comment by tonyteate** [comment]
No problem! Figured it was just a spacing error. Great project you guys have here :+1:

**Pull request merged**
