### PR TITLE
replacing contact form with a newsletter signup

### PR DESCRIPTION
**Pull request by colevscode**
**Changes proposed in this pull request:**
* Replaces test form at bottom of page with newsletter signup form. 
* Adds newletter email to settings

The intention with this change is to use a parser.zaper.com email address, and then create a zap that wires up the email submissions to mailchimp.

**Have you made sure to add:**
- [ ] Tests
- [ ] Documentation

**Screenshots and GIFs**
screen shot 2016-06-04 at 7 49 41 pm

**Deploy notes**

I should merge this so that I can quickly configure the zapier / mailchimp integration.

### CODE REVIEW

**Comment by colevscode** [comment]
screen shot 2016-06-04 at 8 01 43 pm

**Comment by rohitdatta** [comment]
I'm good with this, but I also feel like we should have an example form to show how Formspree works.

**Comment by colevscode** [comment]
Yeah, working on that too. I have an idea for a separate "try it" page that will let you edit the form on the left and submit it on the right. However I think it should also use a separate from email on a different domain to avoid the possibility of spam affecting our deliverability.

**Comment by colevscode** [comment]
Also this is a sort of example form too. (though if we don't have a better test form, users will likely put in bogus email addresses to try out formspree)

**Comment by JamesJosephFinn** [comment]
I'd like to add a feature request to this conversation, if I may.

I'm trying to build an auto-responder using Zapier (screenshot attached). The hiccup comes when I try to access the `name="name"` attribute value. Currently, Formspree sends the value as part of the email body, but in order to access the data, the value should be sent in the header as well, perhaps as `_replytoname`.

What do you think?

screen shot 2016-06-22 at 11 44 02 am

**Comment by rohitdatta** [comment]
Hey @JamesJosephFinn, while we understand that you'd really like this feature, please keep pull request discussions to only be about the request actually opened. To answer your question, it's currently not possible while we use the SendGrid V2 API. The SendGrid V3 API was just released out of beta, so we'll need to fully vet it before committing to switching over, at which point, we should be able to implement something like `From Name <email@email.com>`

**Comment by fiatjaf** [comment]
Should we merge this? I think we should just somehow link to the Formspree testing page before that. It was perfectly good the last time I saw it, I guess, however now I can't even find the URL.

**Comment by fiatjaf** [comment]
@colevscode Any news on the test site? Can I merge this PR? (I've got this same PR conflict-free on my computer already) Should I put a link to the testing site? Where?

**Comment by fiatjaf** [comment]
I've merged this with two links to http://testformspree.com/, one at the top and one at the bottom. I don't think it was great, but at least we'll get this feature live finally.

Please change the wording or placement of these links whenever you can.

**Pull request merged**
