### PR TITLE
Table formatting

### PR DESCRIPTION
**Pull request by fiatjaf**
**Fixes https://trello.com/c/FCYdQLFL and other small things**

**Changes proposed in this pull request:**

* Add a `ridge` border to the submissions table `td`s.
* Make the submissions table horizontally scrollable -- instead of allowing free overflow -- when there are too many fields.
* Submissions values `td`s are limited to 300px.
* Long submission values are truncated to 270 characters, with a link to display the entire value (and a link to hide the entire value when it is shown) (pure HTML, no JS).
* Submissions and forms tables rows are turned into "stacks" on screens smaller than 600px (pure CSS).

**Have you made sure to add:**
- [ ] Tests
- [ ] Documentation

**Screenshots and GIFs**

### CODE REVIEW

**Comment by rohitdatta** [comment]
This still doesn't solve the issue of if there are a lot of fields does it though? I think we need to switch to a vertical view to do that.

**Comment by fiatjaf** [comment]
Yeah, I knew I had forgotten something.

I had originally thought that we could we use the same "responsive" view for when there are a lot of fields. Does that sound good enough? What is "a lot of fields"? More than 7? More than 14?

**Comment by rohitdatta** [comment]
I guess it really depends on the screen size. Maybe we could use CSS to dynamically decide that when the column width hits a certain pixel number it should switch to horizontal layout.

**Comment by colevscode** [comment]
One idea would be to optimize for the most common case. We could look at
our data, and bin submissions into two categories, tests, and valid
submissions. Then we could find the median number of fields on valid
submissions, and design for one standard deviation of that number.

**Comment by fiatjaf** [comment]
6.889999930191485

That's the average fields per submission. I couldn't find a way to do medians.

**Comment by fiatjaf** [comment]
Any ideas here? Can we merge this and try to solve the too-many-fields problem in a different PR?

Also, the card https://trello.com/c/cGQlUBMn has a complaint and a screenshot of the problem.

**Comment by rohitdatta** [comment]
Lets just merge it and try to fix that problem later

**Pull request merged**
